Server:
  name: "bi-server"
  port: 8080

Database:
  network: tcp
  addr: 127.0.0.1:3306
  user: root
  password: mysql0924a..
  db: bi_activity

Redis:
  network: tcp
  addr: 127.0.0.1:6379
  password:
  read_timeout: 5
  write_timeout: 5
  dial_timeout: 2
  pool_size: 10

UserStatus:
  expiration_time: 86400
  login_flag: "login_status"

Jwt: